name: learn-github-actions
on: [push, pull_request]
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
      - run: npm install
      - run: npm test --no-watch --browsers=ChromeHeadlessCI
